server:
  port: 30000
spring:
  application:
    name: service-provider
  cloud:
    nacos:
      discovery:
        server-addr: 10.7.211.69:8848
        namespace: public
        ip: 10.7.211.69
        port: ${server.port}
        group: DEV_GROUP
        cluster-name: shanghai-provider
