server:
  port: 30000
spring:
  application:
    name: service-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.80.200:8848
        namespace: public
        ip: 192.168.80.200
        port: ${server.port}
        group: DEV_GROUP
        cluster-name: shanghai-provider
